openapi: 3.1.3
info:
  description: "Spécification OpenAPI pour la digitalisation des processus administratifs\
    \ \nde la Fédération de Collectivités Agricoles à Madagascar.\nCouvre les fonctionnalité\
    s A à G du cahier des charges.\n"
  title: API Fédération de Collectivités Agricoles
  version: 1.0.0
servers:
- description: Serveur local
  url: http://localhost:8080
paths:
  /collectivites:
    post:
      description: "Vérifie automatiquement les conditions (≥10 membres avec 6 mois\
        \ d’ancienneté, postes occupés, etc.)"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CollectiviteCreation'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collectivite'
          description: Collectivité créée avec succès
        "400":
          content:
            text/plain:
              schema:
                example: Nombre de membres insuffisant ou postes spécifiques non occupés
                type: string
          description: Conditions d’ouverture non remplies
      summary: Créer une nouvelle collectivité (Fonctionnalité A)
      tags:
      - Collectivités
      x-content-type: application/json
      x-accepts:
      - application/json
      - text/plain
  /collectivites/{collectiviteId}/membres:
    post:
      parameters:
      - explode: false
        in: path
        name: collectiviteId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MembreAdmission'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Membre'
          description: Membre admis avec succès
        "400":
          content:
            text/plain:
              schema:
                example: Parrain non valide ou frais d’adhésion non réglés
                type: string
          description: "Conditions non remplies (parrainage, frais, etc.)"
      summary: Admettre un nouveau membre dans une collectivité (Fonctionnalité B)
      tags:
      - Membres
      x-content-type: application/json
      x-accepts:
      - application/json
      - text/plain
  /encaissements:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Encaissement'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Encaissement'
          description: Encaissement enregistré
      summary: Enregistrer un encaissement / cotisation (Fonctionnalité C)
      tags:
      - Trésorerie
      x-content-type: application/json
      x-accepts:
      - application/json
  /collectivites/{collectiviteId}/comptes:
    get:
      parameters:
      - explode: false
        in: path
        name: collectiviteId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Compte'
                type: array
          description: Liste des comptes et soldes
      summary: Lister tous les comptes d’une collectivité (Fonctionnalité D)
      tags:
      - Trésorerie
      x-accepts:
      - application/json
  /comptes/{compteId}/solde:
    get:
      parameters:
      - explode: false
        in: path
        name: compteId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - explode: true
        in: query
        name: at
        required: true
        schema:
          format: date
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Solde'
          description: Solde du compte
      summary: Consulter le solde d’un compte à une date donnée (Fonctionnalité D)
      tags:
      - Trésorerie
      x-accepts:
      - application/json
  /collectivites/{collectiviteId}/activites:
    get:
      parameters:
      - explode: false
        in: path
        name: collectiviteId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Activite'
                type: array
          description: Liste des activités
      summary: Lister les activités d’une collectivité (Fonctionnalité E)
      tags:
      - Activités
      x-accepts:
      - application/json
  /activites:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActiviteCreation'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activite'
          description: Activité créée
      summary: Créer une activité (obligatoire ou exceptionnelle) – Collectivité ou
        Fédération (Fonctionnalité E)
      tags:
      - Activités
      x-content-type: application/json
      x-accepts:
      - application/json
  /activites/{activiteId}/presences:
    post:
      parameters:
      - explode: false
        in: path
        name: activiteId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/Presence'
              type: array
        required: true
      responses:
        "201":
          description: Présences enregistrées
      summary: Enregistrer les présences pour une activité (Fonctionnalité F)
      tags:
      - Assiduite
      x-content-type: application/json
      x-accepts:
      - application/json
  /membres/{membreId}/assiduite:
    get:
      parameters:
      - explode: false
        in: path
        name: membreId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - explode: true
        in: query
        name: du
        required: true
        schema:
          format: date
          type: string
        style: form
      - explode: true
        in: query
        name: au
        required: true
        schema:
          format: date
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TauxAssiduite'
          description: Taux d’assiduité
      summary: Taux d’assiduité d’un membre sur une période (Fonctionnalité F)
      tags:
      - Assiduite
      x-accepts:
      - application/json
  /collectivites/{collectiviteId}/statistiques:
    get:
      parameters:
      - explode: false
        in: path
        name: collectiviteId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - explode: true
        in: query
        name: mois
        required: true
        schema:
          example: 2026-04
          format: date
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatistiquesCollectivite'
          description: Statistiques globales et par membre
      summary: Rapport mensuel complet (Fonctionnalité G)
      tags:
      - Statistiques
      x-accepts:
      - application/json
components:
  schemas:
    Collectivite:
      example:
        nomUnique: nomUnique
        ville: ville
        dateCreation: 2000-01-23
        specialiteAgricole: specialiteAgricole
        numeroUnique: numeroUnique
        id: 0
      properties:
        id:
          format: int64
          type: integer
        numeroUnique:
          type: string
        nomUnique:
          type: string
        ville:
          type: string
        specialiteAgricole:
          type: string
        dateCreation:
          format: date
          type: string
    CollectiviteCreation:
      example:
        nomUnique: nomUnique
        ville: ville
        specialiteAgricole: specialiteAgricole
        membres:
        - dateNaissance: 2000-01-23
          genre: MASCULIN
          adresse: adresse
          parrainId: 0
          telephone: telephone
          nom: nom
          email: email
          prenoms: prenoms
          metier: metier
        - dateNaissance: 2000-01-23
          genre: MASCULIN
          adresse: adresse
          parrainId: 0
          telephone: telephone
          nom: nom
          email: email
          prenoms: prenoms
          metier: metier
      properties:
        nomUnique:
          type: string
        ville:
          type: string
        specialiteAgricole:
          type: string
        membres:
          items:
            $ref: '#/components/schemas/MembreAdmission'
          type: array
      required:
      - nomUnique
      - specialiteAgricole
      - ville
    Membre:
      example:
        dateNaissance: 2000-01-23
        genre: MASCULIN
        adresse: adresse
        telephone: telephone
        id: 0
        poste: PRESIDENT
        nom: nom
        email: email
        prenoms: prenoms
        metier: metier
        dateAdhesion: 2000-01-23
      properties:
        id:
          format: int64
          type: integer
        nom:
          type: string
        prenoms:
          type: string
        dateNaissance:
          format: date
          type: string
        genre:
          enum:
          - MASCULIN
          - FEMININ
          type: string
        adresse:
          type: string
        metier:
          type: string
        telephone:
          type: string
        email:
          type: string
        dateAdhesion:
          format: date
          type: string
        poste:
          enum:
          - PRESIDENT
          - PRESIDENT_ADJOINT
          - TRESORIER
          - SECRETAIRE
          - MEMBRE_CONFIRME
          - MEMBRE_JUNIOR
          type: string
    MembreAdmission:
      example:
        dateNaissance: 2000-01-23
        genre: MASCULIN
        adresse: adresse
        parrainId: 0
        telephone: telephone
        nom: nom
        email: email
        prenoms: prenoms
        metier: metier
      properties:
        nom:
          type: string
        prenoms:
          type: string
        dateNaissance:
          format: date
          type: string
        genre:
          enum:
          - MASCULIN
          - FEMININ
          type: string
        adresse:
          type: string
        metier:
          type: string
        telephone:
          type: string
        email:
          type: string
        parrainId:
          format: int64
          type: integer
      required:
      - adresse
      - dateNaissance
      - email
      - genre
      - metier
      - nom
      - parrainId
      - prenoms
      - telephone
    Encaissement:
      example:
        modePaiement: ESPECES
        montant: 5.962133916683182
        id: 0
        membreId: 6
        collectiviteId: 1
        type: PERIODIQUE
        dateEncaissement: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          format: int64
          type: integer
        membreId:
          format: int64
          type: integer
        collectiviteId:
          format: int64
          type: integer
        montant:
          format: decimal
          type: number
        dateEncaissement:
          format: date-time
          type: string
        modePaiement:
          enum:
          - ESPECES
          - VIREMENT_BANCAIRE
          - MOBILE_MONEY
          type: string
        type:
          enum:
          - PERIODIQUE
          - PONCTUELLE
          type: string
      required:
      - collectiviteId
      - dateEncaissement
      - membreId
      - modePaiement
      - montant
    Compte:
      example:
        solde: 1.4658129805029452
        id: 0
        collectiviteId: 6
        type: CAISSE
        devise: MGA
      properties:
        id:
          format: int64
          type: integer
        collectiviteId:
          format: int64
          type: integer
        type:
          enum:
          - CAISSE
          - BANCAIRE
          - MOBILE_MONEY
          type: string
        solde:
          format: decimal
          type: number
        devise:
          default: MGA
          type: string
    Solde:
      example:
        date: 2000-01-23
        compteId: 0
        solde: 6.027456183070403
        devise: MGA
      properties:
        compteId:
          format: int64
          type: integer
        solde:
          format: decimal
          type: number
        date:
          format: date
          type: string
        devise:
          default: MGA
          type: string
    Activite:
      example:
        date: 2000-01-23T04:56:07.000+00:00
        cible: TOUS
        obligatoire: true
        id: 0
        collectiviteId: 6
        type: ASSEMBLEE_GENERALE_MENSUELLE
      properties:
        id:
          format: int64
          type: integer
        collectiviteId:
          format: int64
          type: integer
        type:
          enum:
          - ASSEMBLEE_GENERALE_MENSUELLE
          - FORMATION_JUNIOR
          - EXCEPTIONNELLE
          - AG_ANNUELLE
          type: string
        date:
          format: date-time
          type: string
        obligatoire:
          type: boolean
        cible:
          enum:
          - TOUS
          - JUNIORS
          type: string
    ActiviteCreation:
      example:
        date: 2000-01-23T04:56:07.000+00:00
        cible: TOUS
        obligatoire: true
        type: ASSEMBLEE_GENERALE_MENSUELLE
        collectiviteId: 0
      properties:
        type:
          enum:
          - ASSEMBLEE_GENERALE_MENSUELLE
          - FORMATION_JUNIOR
          - EXCEPTIONNELLE
          - AG_ANNUELLE
          type: string
        date:
          format: date-time
          type: string
        obligatoire:
          type: boolean
        cible:
          enum:
          - TOUS
          - JUNIORS
          type: string
        collectiviteId:
          format: int64
          type: integer
      required:
      - date
      - obligatoire
      - type
    Presence:
      example:
        membreId: 0
        present: true
        motifAbsence: motifAbsence
      properties:
        membreId:
          format: int64
          type: integer
        present:
          type: boolean
        motifAbsence:
          type: string
      required:
      - membreId
      - present
    TauxAssiduite:
      example:
        periodeDu: 2000-01-23
        taux: 92.5
        membreId: 0
        periodeAu: 2000-01-23
      properties:
        membreId:
          format: int64
          type: integer
        periodeDu:
          format: date
          type: string
        periodeAu:
          format: date
          type: string
        taux:
          example: 92.5
          format: float
          type: number
    StatistiquesCollectivite:
      example:
        statistiquesParMembre:
        - montantEncaisse: 2.3021358869347655
          montantImpaye: 7.061401241503109
          membreId: 5
          tauxAssiduite: 5.637377
        - montantEncaisse: 2.3021358869347655
          montantImpaye: 7.061401241503109
          membreId: 5
          tauxAssiduite: 5.637377
        nombreMembresActifs: 6
        collectiviteId: 0
        tauxAssiduiteGlobale: 1.4658129
        mois: 2000-01-23
      properties:
        collectiviteId:
          format: int64
          type: integer
        mois:
          format: date
          type: string
        nombreMembresActifs:
          type: integer
        tauxAssiduiteGlobale:
          format: float
          type: number
        statistiquesParMembre:
          items:
            $ref: '#/components/schemas/StatistiqueMembre'
          type: array
    StatistiqueMembre:
      example:
        montantEncaisse: 2.3021358869347655
        montantImpaye: 7.061401241503109
        membreId: 5
        tauxAssiduite: 5.637377
      properties:
        membreId:
          format: int64
          type: integer
        tauxAssiduite:
          format: float
          type: number
        montantEncaisse:
          format: decimal
          type: number
        montantImpaye:
          format: decimal
          type: number

